/*
 * MattX - The Modern Single System Image (SSI) Cluster
 * 
 * Copyright (c) 2026 by Matthias Rechenburg
 * All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Commercial licensing options are available upon request.
 */
 
# MattX Cluster Configuration
INTERFACE=enp1s0
MULTICAST_GROUP=239.0.0.1
PORT=7225
# Set to 0 to auto-generate Node ID from MAC address
NODE_ID=0
# configure the behavior of the cluster
MIGRATE_NETWORK_IO=true     // Set to true to enable network I/O migration, false to disable
MIGRATE_FILE_IO=true        // Set to true to enable file I/O migration, false to disable
MATTXFS_ENABLED=true        // Set to true to enable MattXFS, false to disable
DFSA_DIR=/mnt/shared        // Directory for Direct File System Access (DFSA) 
