 MattX Cluster Configuration
INTERFACE=enp1s0
MULTICAST_GROUP=239.0.0.1
PORT=7225
# Set to 0 to auto-generate Node ID from MAC address
NODE_ID=0
# configure the behavior of the cluster
MIGRATE_NETWORK_IO=true     // Set to true to enable network I/O migration, false to disable
MIGRATE_FILE_IO=true        // Set to true to enable file I/O migration, false to disable
MATTXFS_ENABLED=0           // Set to 1 to enable MattXFS, 0 to disable

