#!/bin/bash

# load module - need to be in mattx/ directory
mload
# start mattx-discd via systemd
dstart
# apply MattX configuration
echo "balancer 0" > /proc/mattx/admin
echo "include pvmchess-client,mpichess-client,migtest,dfsatest,epolltest" > /proc/mattx/admin

# mount mattxfs
echo "mounting mattxfs at /mattxfs"
sudo mount -t mattxfs none /mattxfs

# no mattxfs vfs syscalls for testing
echo "debug 1" > /proc/mattx/admin
echo "config MATTXFS_ENABLED=0" > /proc/mattx/admin