#!/bin/bash

#sudo sed -i -e "s/MATTXFS_ENABLED=true/MATTXFS_ENABLED=false/g" /etc/mattx.conf


MATTX_NIC=$(ip a s | grep enp.*: | awk '{print $2}' | cut -d: -f1 | head -n1)
echo "MATTX_NIC: $MATTX_NIC"
sudo sed -i -e "s/INTERFACE=.*/INTERFACE=$MATTX_NIC/g" /etc/mattx.conf


# load module - need to be in mattx/ directory
mload
# start mattx-discd via systemd
dstart
# apply MattX configuration
#echo "balancer 0" > /proc/mattx/admin
echo "debug 1" > /proc/mattx/admin
echo "include pvmchess-client,mpichess-client,migtest,dfsatest,epolltest" > /proc/mattx/admin

# mount mattxfs
echo "mounting mattxfs at /mattxfs"
sudo mount -t mattxfs none /mattxfs

